CREATE DATABASE IF NOT EXISTS messstation DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE messstation;
CREATE TABLE Gebaeude(
    Ge_Nr INT PRIMARY KEY AUTO_INCREMENT,
    Gebaeude_Name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE Raum(
    Ra_Nr INT PRIMARY KEY AUTO_INCREMENT,
    Raum_Name VARCHAR(100) NOT NULL UNIQUE,
    Ge_Nr INT,
    FOREIGN KEY (Ge_Nr) REFERENCES Gebaeude(Ge_Nr) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Positionstelle(
    Pos_Nr INT PRIMARY KEY AUTO_INCREMENT,
    Position VARCHAR(150) NOT NULL UNIQUE,
    Ra_Nr INT,
    FOREIGN KEY (Ra_Nr) REFERENCES Raum(Ra_Nr) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Messung(
    Messung_ID INT PRIMARY KEY AUTO_INCREMENT,
    co2_Wert VARCHAR(100),
    temperatur_Wert VARCHAR(100),
    feuchtigkeit_Wert VARCHAR(100),
    cTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP(),
    Pos_Nr INT,
    FOREIGN KEY (Pos_Nr) REFERENCES Positionstelle(Pos_Nr) ON DELETE RESTRICT ON UPDATE CASCADE
);